#include "code_generator.h"
#include "utils.h"
#include <sstream>

// 将vector转换为C++数组初始化格式
static std::string vectorToArray(const std::string& name, const std::vector<int>& vec) {
    std::stringstream ss;
    ss << "static const int " << name << "[" << vec.size() << "] = {\n    ";
    for (size_t i = 0; i < vec.size(); i++) {
        ss << vec[i];
        if (i < vec.size() - 1) {
            ss << ", ";
            if ((i + 1) % 16 == 0) ss << "\n    ";
        }
    }
    ss << "\n};\n";
    return ss.str();
}

// 生成C++词法分析器代码
void generateCode(const DriverTable& table, const std::string& outputFile) {
    std::stringstream code;
    
    // 文件头
    code << "/* Generated by SeuLex - Lexical Analyzer */\n\n";
    code << "#include <iostream>\n";
    code << "#include <fstream>\n";
    code << "#include <string>\n";
    code << "#include <vector>\n";
    code << "#include <cstring>\n\n";
    
    // 用户定义部分（part1）
    if (!g_data.part1.empty()) {
        code << "/* User declarations */\n";
        code << g_data.part1 << "\n";
    }
    
    // 宏定义
    code << "#define START_STATE " << table.startState << "\n";
    code << "#define YY_NULL 0\n\n";
    
    // 全局变量
    code << "/* Global variables */\n";
    code << "static char* yy_file_buffer = nullptr;\n";
    code << "static char* yy_cp = nullptr;\n";
    code << "static int yy_leng = 0;\n";
    code << "static std::string yytext;\n";
    code << "static int yy_line_num = 1;\n";
    code << "static int yy_col_num = 1;\n\n";
    
    // 驱动表
    code << "/* Driver tables */\n";
    code << vectorToArray("yy_edge_col", table.yy_edge_col);
    code << "\n";
    code << vectorToArray("yy_state_row", table.yy_state_row);
    code << "\n";
    code << vectorToArray("yy_next", table.yy_next);
    code << "\n";
    code << vectorToArray("yy_accept", table.yy_accept);
    code << "\n";
    
    // 前向声明
    code << "/* Function declarations */\n";
    code << "int yylex();\n";
    code << "void yy_init(const char* filename);\n";
    code << "void yy_cleanup();\n";
    code << "int find_action(int action_idx, const char* yytext, int yyleng);\n\n";
    
    // 动作函数
    code << "/* Action functions */\n";
    code << "int find_action(int action_idx, const char* yytext, int yyleng) {\n";
    code << "    switch (action_idx) {\n";
    
    for (const auto& rule : table.actionRules) {
        code << "        case " << rule.ruleId << ":\n";
        bool hasReturn = false;
        for (const auto& action : rule.actions) {
            code << "            " << action << ";\n";
            if (action.find("return") != std::string::npos) {
                hasReturn = true;
            }
        }
        if (!hasReturn) {
            code << "            return -1;  // Continue scanning\n";
        }
        code << "            break;\n";
    }
    
    code << "        default:\n";
    code << "            break;\n";
    code << "    }\n";
    code << "    return 0;\n";
    code << "}\n\n";
    
    // yylex函数
    code << "/* Lexical analyzer main function */\n";
    code << "int yylex() {\n";
    code << "    if (!yy_cp || !*yy_cp) return YY_NULL;\n\n";
    code << "    int current_state = START_STATE;\n";
    code << "    char* yy_last_accepting_char_ptr = nullptr;\n";
    code << "    int yy_last_accepting_state = -1;\n";
    code << "    char* yy_start_ptr = yy_cp;\n\n";
    code << "    while (true) {\n";
    code << "        char c = *yy_cp;\n";
    code << "        int col = yy_edge_col[(unsigned char)c];\n\n";
    code << "        if (col == 0) {\n";
    code << "            // Character not in alphabet\n";
    code << "            if (yy_last_accepting_state != -1) {\n";
    code << "                // Backtrack to last accepting state\n";
    code << "                yy_cp = yy_last_accepting_char_ptr;\n";
    code << "                char yy_saved = *yy_cp;\n";
    code << "                *yy_cp = '\\0';\n";
    code << "                yytext = std::string(yy_start_ptr);\n";
    code << "                yy_leng = yytext.length();\n";
    code << "                int action_idx = yy_accept[yy_last_accepting_state] - 1;\n";
    code << "                *yy_cp = yy_saved;  // Restore original character\n";
    code << "                yy_last_accepting_state = -1;\n";
    code << "                yy_start_ptr = yy_cp;\n";
    code << "                int result = find_action(action_idx, yytext.c_str(), yy_leng);\n";
    code << "                if (result != -1) return result;\n";
    code << "                current_state = START_STATE;  // Reset state for continue\n";
    code << "                continue;  // Continue scanning for rules without return\n";
    code << "            } else {\n";
    code << "                // No accepting state - skip character\n";
    code << "                yy_cp++;\n";
    code << "                // Update position tracking for skipped character\n";
    code << "                if (c == '\\n') {\n";
    code << "                    yy_line_num++;\n";
    code << "                    yy_col_num = 1;\n";
    code << "                } else {\n";
    code << "                    yy_col_num++;\n";
    code << "                }\n";
    code << "                // Check if we've reached end of input\n";
    code << "                if (*yy_cp == '\\0') {\n";
    code << "                    return YY_NULL;\n";
    code << "                }\n";
    code << "                yy_start_ptr = yy_cp;\n";
    code << "                current_state = START_STATE;\n";
    code << "                continue;\n";
    code << "            }\n";
    code << "        }\n\n";
    code << "        int next_state = yy_next[yy_state_row[current_state] + col];\n\n";
    code << "        if (next_state == -1) {\n";
    code << "            // No transition - check for accepting state\n";
    code << "            if (yy_last_accepting_state != -1) {\n";
    code << "                // Backtrack to last accepting state\n";
    code << "                yy_cp = yy_last_accepting_char_ptr;\n";
    code << "                char yy_saved = *yy_cp;\n";
    code << "                *yy_cp = '\\0';\n";
    code << "                yytext = std::string(yy_start_ptr);\n";
    code << "                yy_leng = yytext.length();\n";
    code << "                int action_idx = yy_accept[yy_last_accepting_state] - 1;\n";
    code << "                *yy_cp = yy_saved;  // Restore original character\n";
    code << "                yy_last_accepting_state = -1;\n";
    code << "                yy_start_ptr = yy_cp;\n";
    code << "                int result = find_action(action_idx, yytext.c_str(), yy_leng);\n";
    code << "                if (result != -1) return result;\n";
    code << "                current_state = START_STATE;  // Reset state for continue\n";
    code << "                continue;  // Continue scanning for rules without return\n";
    code << "            } else {\n";
    code << "                // No accepting state - skip character\n";
    code << "                yy_cp++;\n";
    code << "                // Update position tracking for skipped character\n";
    code << "                if (c == '\\n') {\n";
    code << "                    yy_line_num++;\n";
    code << "                    yy_col_num = 1;\n";
    code << "                } else {\n";
    code << "                    yy_col_num++;\n";
    code << "                }\n";
    code << "                // Check if we've reached end of input\n";
    code << "                if (*yy_cp == '\\0') {\n";
    code << "                    return YY_NULL;\n";
    code << "                }\n";
    code << "                yy_start_ptr = yy_cp;\n";
    code << "                current_state = START_STATE;\n";
    code << "                continue;\n";
    code << "            }\n";
    code << "        }\n\n";
    code << "        // Check if current state is accepting\n";
    code << "        if (yy_accept[next_state] != 0) {\n";
    code << "            yy_last_accepting_state = next_state;\n";
    code << "            yy_last_accepting_char_ptr = yy_cp + 1;\n";
    code << "        }\n\n";
    code << "        // Update position tracking\n";
    code << "        if (c == '\\n') {\n";
    code << "            yy_line_num++;\n";
    code << "            yy_col_num = 1;\n";
    code << "        } else {\n";
    code << "            yy_col_num++;\n";
    code << "        }\n\n";
    code << "        yy_cp++;\n";
    code << "        current_state = next_state;\n\n";
    code << "        // Check for end of input\n";
    code << "        if (*yy_cp == '\\0') {\n";
    code << "            if (yy_last_accepting_state != -1) {\n";
    code << "                yytext = std::string(yy_start_ptr);\n";
    code << "                yy_leng = yytext.length();\n";
    code << "                int action_idx = yy_accept[yy_last_accepting_state] - 1;\n";
    code << "                yy_last_accepting_state = -1;\n";
    code << "                yy_start_ptr = yy_cp;\n";
    code << "                int result = find_action(action_idx, yytext.c_str(), yy_leng);\n";
    code << "                if (result != -1) return result;\n";
    code << "                return YY_NULL;  // Continue would cause infinite loop at EOF\n";
    code << "            }\n";
    code << "            return YY_NULL;\n";
    code << "        }\n";
    code << "    }\n";
    code << "}\n\n";
    
    // yy_init函数
    code << "/* Initialize lexer with input file */\n";
    code << "void yy_init(const char* filename) {\n";
    code << "    std::ifstream file(filename, std::ios::binary);\n";
    code << "    if (!file.is_open()) {\n";
    code << "        std::cerr << \"Error: Cannot open file \" << filename << std::endl;\n";
    code << "        return;\n";
    code << "    }\n\n";
    code << "    file.seekg(0, std::ios::end);\n";
    code << "    std::streamsize size = file.tellg();\n";
    code << "    file.seekg(0, std::ios::beg);\n\n";
    code << "    yy_file_buffer = new char[size + 2];\n";
    code << "    file.read(yy_file_buffer, size);\n";
    code << "    yy_file_buffer[size] = '\\0';\n";
    code << "    yy_file_buffer[size + 1] = '\\0';\n\n";
    code << "    yy_cp = yy_file_buffer;\n";
    code << "    yy_line_num = 1;\n";
    code << "    yy_col_num = 1;\n";
    code << "}\n\n";
    
    // yy_cleanup函数
    code << "/* Cleanup lexer resources */\n";
    code << "void yy_cleanup() {\n";
    code << "    if (yy_file_buffer) {\n";
    code << "        delete[] yy_file_buffer;\n";
    code << "        yy_file_buffer = nullptr;\n";
    code << "    }\n";
    code << "    yy_cp = nullptr;\n";
    code << "}\n\n";
    
    // input函数 - 读取下一个字符
    code << "/* Read next character from input */\n";
    code << "int input(void) {\n";
    code << "    if (!yy_cp || !*yy_cp) return 0;\n";
    code << "    return *yy_cp++;\n";
    code << "}\n\n";
    
    // unput函数 - 放回字符
    code << "/* Put back character to input */\n";
    code << "void unput(int c) {\n";
    code << "    if (yy_cp > yy_file_buffer) {\n";
    code << "        *(--yy_cp) = c;\n";
    code << "    }\n";
    code << "}\n\n";
    
    // yywrap函数 - 文件结束处理（如果用户没有定义）
    bool hasYywrap = false;
    for (const auto& rule : table.actionRules) {
        for (const auto& action : rule.actions) {
            if (action.find("yywrap") != std::string::npos) {
                hasYywrap = true;
                break;
            }
        }
        if (hasYywrap) break;
    }
    
    // 检查用户代码中是否定义了 yywrap
    if (!hasYywrap && g_data.part4.find("yywrap") == std::string::npos) {
        code << "/* Wrap up - called at end of input */\n";
        code << "int yywrap(void) {\n";
        code << "    return 1;  // Default: no more input files\n";
        code << "}\n\n";
    }
    
    // 用户代码部分（part4）
    if (!g_data.part4.empty()) {
        code << "/* User code */\n";
        code << g_data.part4 << "\n";
    }
    
    // 默认main函数（如果用户没有提供）
    code << "/* Default main function */\n";
    code << "#ifndef YY_MAIN_DEFINED\n";
    code << "int main(int argc, char* argv[]) {\n";
    code << "    if (argc < 2) {\n";
    code << "        std::cerr << \"Usage: \" << argv[0] << \" <input_file>\" << std::endl;\n";
    code << "        return 1;\n";
    code << "    }\n\n";
    code << "    yy_init(argv[1]);\n\n";
    code << "    int token;\n";
    code << "    while ((token = yylex()) != YY_NULL) {\n";
    code << "        // Token processing is done in actions\n";
    code << "    }\n\n";
    code << "    yy_cleanup();\n";
    code << "    return 0;\n";
    code << "}\n";
    code << "#endif\n";
    
    // 写入文件
    writeFile(outputFile, code.str());
    
    std::cout << "Generated lexer code: " << outputFile << std::endl;
}
